name: Build Extension
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install -g crx

    - name: Package the Chrome Extension
      run: |
        FILENAME="Adblock-Extension-v${GITHUB_SHA::7}.crx"
        crx pack ./ -o ./$FILENAME
        echo "FILENAME=$FILENAME" >> $GITHUB_ENV

    - name: Release script
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ env.FILENAME }}
        name: Adblock Extension ${{ env.FILENAME }}
        tag_name: ${{ env.FILENAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete older releases (after new release is created)
      uses: dev-drprasad/delete-older-releases@v0.3.4
      with:
        keep_latest: 1
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 1
