name: Build CRX

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Set up Node.js
      uses: actions/setup-node@main
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install -g crx  # Cài đặt công cụ crx (không cần mật khẩu)

    - name: Package the Chrome Extension
      run: |
        crx pack ./ -o ./Adblock.crx

    - name: Generate date
      run: echo "DATE=$(date +%F )" >> $GITHUB_ENV
       
    - name: Release script 
      uses: softprops/action-gh-release@v1
      with:
        files: Adblock.crx
        name: Extension ${{ env.DATE }}
        tag_name: ${{ env.DATE }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete older releases
      uses: dev-drprasad/delete-older-releases@v0.2.1
      with:
        keep_latest: 1
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 1
