name: Build CRX

on:
  push:
    branches:
      - main  # hoặc bạn có thể thay đổi thành branch khác nếu muốn
  pull_request:
    branches:
      - main  # khi có PR trên branch chính

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Set up Node.js
      uses: actions/setup-node@main
      with:
        node-version: '20'  # Chọn phiên bản Node.js bạn muốn

    - name: Install dependencies
      run: |
        npm install -g crx  # Cài đặt công cụ crx (không cần mật khẩu)

    - name: Package the Chrome Extension
      run: |
        # Đóng gói extension thành CRX mà không cần mật khẩu
        crx pack ./ -o ./my-extension.crx

    - name: Upload CRX as Artifact
      uses: actions/upload-artifact@main
      with:
        name: my-extension.crx
        path: ./my-extension.crx

    - name: Cleanup Previous Workflow Runs
      uses: actions/github-script@main
      with:
        script: |
          const allRuns = [];
          let page = 1;

          while (true) {
            const { data: runs } = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'patch.yml',
              per_page: 100,
              page,
            });

            if (runs.workflow_runs.length === 0) break;
            allRuns.push(...runs.workflow_runs);
            page++;
          }

          console.log(`Found ${allRuns.length} workflow runs.`);

          for (const run of allRuns) {
            if (run.id !== context.runId) {
              console.log(`Deleting workflow run ID: ${run.id}`);
              await github.rest.actions.deleteWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: run.id,
              });
            }
          }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
